### ISSUE TITLE
Brainstorm machine statistics to display in web app

### ISSUE THREAD

**Issue by dominicrutk** [bioneos/alcove#44]
Each machine should have more detailed statistics on its individual page than the main dashboard. What should those statistics be?

**Comment by osandvold302** [comment]
I'd like to know the size of each backup directory on disk for each machine

**Comment by DominicRutkowski** [comment]
This is what the machine dashboard looks like currently.
![screencapture-localhost-3000-machine-docker-container-2019-07-15-15_49_51](https://user-images.githubusercontent.com/29609814/61248221-42022000-a718-11e9-838c-77cb04883bea.png)

**Comment by dominicrutk** [comment]
This issue is essentially resolved—we have a working machine dashboard. We could always change the statistics on it, but that can be in a new issue.
