### ISSUE TITLE
Combined logs message

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/alcove#67]
Certain log messages belong in both logs:
```
2020-01-12T17:33:52.075] [DEBUG] default - Scheduling backup for "Skylinux"
[2020-01-12T17:33:52.075] [INFO] Skylinux - Scheduling backup at Sun Jan 12 2020 17:56:00 GMT+0000 (UTC) for "Skylinux"
```
For example that second INFO message could go into the main log as well as the machine specific, I think. 

I think we can achieve this with minor changes to the `lib/rsync.js` code. Simply add a reference to the main logger and whenever something is important enough to go to both, send the message to both loggers. (It would make sense to create a simple function in this module for that).

**Comment by dominicrutk** [comment]
As mentioned in #79, we might want to revisit this to find a more elegant solution.
