### ISSUE TITLE
Machine dashboard calendar widget

### ISSUE THREAD

**Issue by dominicrutk** [bioneos/alcove#77]
Once #75 is resolved, we can replace the manually-drawn calendar on the machine dashboard with a Fomantic-UI [calendar widget](https://fomantic-ui.com/modules/calendar.html). We would be able to highlight specific dates and go back in time further than the previous month. The calendar widget is primarily designed as a date picker form input, but disabling it and making it permanently open should make it work as a calendar view instead of an input.

**Comment by GautamSharda** [comment]
test comment

**Comment by sgdavis1** [comment]
Closed by PR #104
