### ISSUE TITLE
Dashboard date popup displays as integer

### ISSUE THREAD

**Issue by dominicrutk** [bioneos/alcove#90]
On the main dashboard page, a popup opens when the user hovers over the "Total Backup Size" segment. The popup displays information about the accuracy of the total backup size measurement (i.e., whether the measurement completed) and how recently it was completed (i.e. a date). Currently, the date is displaying in integer form, which is not useful information for humans (see attached screenshot).

<img width="1440" alt="Screen Shot 2021-06-18 at 11 52 00 AM" src="https://user-images.githubusercontent.com/29609814/122594833-3074d180-d02d-11eb-88a7-526d5b79df03.png">

This date should be displayed as a date/time like the one on the "Running since" segment in the screenshot. There should be a function in `util.js` to handle this. I think you might need to convert the integer to a Date object before passing it to the relevant util function.

**Comment by kartikth40** [comment]
Ok I'll work on this.

**Comment by machu23** [comment]
I can do this one

**Comment by sgdavis1** [comment]
Closed by #103
