### ISSUE TITLE
Real CSS framework

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/alcove#96]
Lets add a real CSS framework to help improving the Look & Feel of the UI. My top choices would be:

* https://fomantic-ui.com/
* https://bulma.io/

Or we could go the really minimal route with something like:
* http://getskeleton.com/

**Comment by dominicrutk** [comment]
I believe we already have Fomantic-UI installed for things like tables and certain other little things (segments?), but it is underutilized. This means we have a bit of custom CSS, which clashes in several places with Fomantic.

**Comment by sgdavis1** [comment]
Well that explains it! We should therefore take a big pass through the
system to clean up everything we can. I'll reject this issue and create a
new one.
